const {app,BrowserWindow,ipcMain,Menu,Notification,Tray,nativeImage,dialog}=require('electron');
const path=require('path'),fs=require('fs'),{spawn}=require('child_process'),WebSocket=require('ws');
const {autoUpdater}=require('electron-updater');
const ROOT=path.join(__dirname,'..'),DATA=app.isPackaged?path.join(app.getPath('appData'),'Codex Usage Monitor'):path.join(ROOT,'.appdata'),FILE=path.join(DATA,'monitor.json'),PROFILE=path.join(DATA,'ChromeProfile');
const APP_ICON=path.join(ROOT,'assets','icon.png');
const URL_USAGE='https://chatgpt.com/settings/usage?tab=overview',PORT=9223,DEF={pollMinutes:5,autoStart:true,sound:true,quietStart:22,quietEnd:7,thresholds:[20,10,5],theme:'dark',language:'vi',alwaysOnTop:false,mini:false};
app.setPath('userData',DATA); app.commandLine.appendSwitch('disk-cache-dir',path.join(DATA,'Cache'));
if(!app.requestSingleInstanceLock())app.quit();
let win,tray,chrome,fast,regular,reading=false,visible=false,fail=0;
let saved=(()=>{try{return JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{return{}}})();
let settings={...DEF,...saved.settings},history=saved.history||[],data=saved.data||{status:'Đang khởi động…',connection:'loading',updatedAt:null,stale:true,limits:[]};
const save=()=>{fs.mkdirSync(DATA,{recursive:true});history=history.filter(x=>x.at>Date.now()-2592e6).slice(-3000);fs.writeFileSync(FILE,JSON.stringify({settings,history,data},null,2))};
const color=()=>{if(!data.limits.length||data.connection==='error')return'#94a3b8';let n=Math.min(...data.limits.map(x=>x.remaining));return n<=10?'#fb7185':n<=20?'#fbbf24':'#38bdf8'};
const icon=()=>nativeImage.createFromPath(path.join(ROOT,'assets','icon-16.png'));
function publish(next,persist=false){data={...next,settings,history:history.filter(x=>x.at>Date.now()-6048e5).slice(-300)};if(persist)save();win?.webContents.send('usage',data);if(tray){tray.setImage(icon());tray.setToolTip(data.limits.map(x=>`${x.kind==='fiveHour'?'5 giờ':'Tuần'} ${x.remaining}%`).join(' • ')||data.status);menu()}}
function createWindow(){win=new BrowserWindow({width:settings.mini?360:520,height:settings.mini?330:700,minWidth:340,minHeight:300,show:false,alwaysOnTop:settings.alwaysOnTop,autoHideMenuBar:true,title:'Codex Usage Monitor',icon:APP_ICON,webPreferences:{preload:path.join(__dirname,'preload-v2.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'index-update.html'));win.on('close',e=>{if(!app.isQuitting){e.preventDefault();win.hide()}})}
function chromePath(){return[path.join(process.env.PROGRAMFILES||'','Google','Chrome','Application','chrome.exe'),path.join(process.env['PROGRAMFILES(X86)']||'','Google','Chrome','Application','chrome.exe'),path.join(process.env.LOCALAPPDATA||'','Google','Chrome','Application','chrome.exe')].find(fs.existsSync)}
function startFast(){if(!fast)fast=setInterval(read,2000)} function stopFast(){clearInterval(fast);fast=null}
function schedule(){clearInterval(regular);regular=setInterval(read,Math.max(1,settings.pollMinutes)*60000)}
function launch(show=false){let exe=chromePath();if(!exe)return publish({...data,status:'Không tìm thấy Chrome',connection:'error',stale:true});visible=show;let a=[`--remote-debugging-port=${PORT}`,`--user-data-dir=${PROFILE}`,'--no-first-run','--no-default-browser-check',`--app=${URL_USAGE}`];if(!show)a.push('--start-minimized');chrome=spawn(exe,a,{stdio:'ignore'});startFast()}
function cdp(url,method,params={}){return new Promise((ok,no)=>{let w=new WebSocket(url),t=setTimeout(()=>{w.terminate();no(Error('Chrome không phản hồi'))},8000);w.once('open',()=>w.send(JSON.stringify({id:1,method,params})));w.on('message',b=>{let m=JSON.parse(b);if(m.id!==1)return;clearTimeout(t);w.close();m.error?no(Error(m.error.message)):ok(m.result)});w.once('error',()=>no(Error('Không kết nối được Chrome')))});}
async function closeChrome(){try{let v=await fetch(`http://127.0.0.1:${PORT}/json/version`).then(r=>r.json());await cdp(v.webSocketDebuggerUrl,'Browser.close')}catch{chrome?.kill()}}
function resetAt(s){let n=0;for(let[r,u]of[[/(\d+)\s*(?:d|day|ngày)/i,864e5],[/(\d+)\s*(?:h|hour|giờ)/i,36e5],[/(\d+)\s*(?:m|min|phút)/i,6e4]]){let m=s.match(r);if(m)n+=+m[1]*u}return n?Date.now()+n:null}
function forecast(kind,remain){let p=history.filter(x=>x.kind===kind&&x.at>Date.now()-864e5).slice(-30);if(p.length<2)return null;let h=(p.at(-1).at-p[0].at)/36e5,spent=p[0].remaining-p.at(-1).remaining;if(h<=0||spent<=0)return null;let ratePerHour=spent/h;return{ratePerHour,emptyAt:Date.now()+remain/ratePerHour*36e5}}
async function minimize(tab){try{let x=await cdp(tab.webSocketDebuggerUrl,'Browser.getWindowForTarget',{targetId:tab.id});await cdp(tab.webSocketDebuggerUrl,'Browser.setWindowBounds',{windowId:x.windowId,bounds:{windowState:'minimized'}})}catch{}}
function hideChromeWindow(){let profile=PROFILE.replace(/'/g,"''");let cmd=`Add-Type -Name Win32 -Namespace Native -MemberDefinition '[DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);'; Get-CimInstance Win32_Process | Where-Object { $_.Name -eq 'chrome.exe' -and $_.CommandLine -like '*${profile}*' } | ForEach-Object { $p=Get-Process -Id $_.ProcessId -ErrorAction SilentlyContinue; if($p.MainWindowHandle -ne 0){[Native.Win32]::ShowWindow($p.MainWindowHandle,0)|Out-Null} }`;spawn('powershell.exe',['-NoProfile','-WindowStyle','Hidden','-Command',cmd],{windowsHide:true,stdio:'ignore'}).unref()}
async function read(){if(reading)return;reading=true;try{let tabs=await fetch(`http://127.0.0.1:${PORT}/json`).then(r=>r.json()),tab=tabs.find(x=>x.type==='page'&&x.url.includes('/settings/usage'));if(!tab)throw Error('Chưa mở trang Usage');let exp=`(()=>{let t=document.body?.innerText||'',l=t.split(/\\n+/).map(x=>x.trim()).filter(Boolean);return{title:document.title,pct:[...t.matchAll(/(?:Còn lại|remaining)\\s*(\\d{1,3})%|(\\d{1,3})%\\s*(?:left|remaining)/gi)].map(m=>+(m[1]||m[2])),reset:l.filter(x=>/(?:Đặt lại sau|resets? in)/i.test(x)).slice(0,2)}})()`;let r=(await cdp(tab.webSocketDebuggerUrl,'Runtime.evaluate',{expression:exp,returnByValue:true})).result.value;if(!r?.pct?.length)throw Error(r?.title==='Just a moment...'?'Cloudflare đang kiểm tra':'Trang chưa sẵn sàng');let now=Date.now(),limits=r.pct.slice(0,2).map((remaining,i)=>{let kind=i?'weekly':'fiveHour',reset=r.reset[i]||'';history.push({at:now,kind,remaining});return{kind,name:i?'Giới hạn hàng tuần':'Giới hạn trong 5 giờ',remaining,reset,resetAt:resetAt(reset),forecast:forecast(kind,remaining)}});fail=0;publish({status:'Đang theo dõi',connection:'online',updatedAt:now,stale:false,limits},true);notify(limits);stopFast();hideChromeWindow();visible=false}catch(e){if(++fail>=3){publish({...data,status:`Mất kết nối: ${e.message}`,connection:'error',stale:true});if(/fetch|kết nối|ECONNREFUSED/i.test(String(e)))setTimeout(()=>launch(false),Math.min(60000,fail*5000))}}finally{reading=false}}
function quiet(){let h=new Date().getHours(),a=settings.quietStart,b=settings.quietEnd;return a===b?false:a<b?h>=a&&h<b:h>=a||h<b}
function notify(limits){for(let l of limits)for(let t of settings.thresholds){let k=`${l.kind}:${t}:${Math.floor((l.resetAt||0)/36e5)}`;if(l.remaining<=t&&!saved[k]&&!quiet()){saved[k]=1;new Notification({title:'Codex sắp hết hạn mức',body:`${l.name}: còn ${l.remaining}%. ${l.reset}`,silent:!settings.sound}).show()}}}
async function login(){stopFast();await closeChrome();setTimeout(()=>launch(true),800);publish({...data,status:'Đăng nhập trong Chrome; dashboard sẽ tự cập nhật.',connection:'loading'})}
function menu(){tray.setContextMenu(Menu.buildFromTemplate([...data.limits.map(x=>({label:`${x.kind==='fiveHour'?'5 giờ':'Tuần'}: ${x.remaining}% • ${x.reset}`,enabled:false})),{label:data.status,enabled:false},{type:'separator'},{label:'Mở dashboard',click:()=>win.show()},{label:'Làm mới ngay',click:()=>{startFast();read()}},{label:'Kết nối lại',click:login},{type:'separator'},{label:'Thoát',click:()=>{app.isQuitting=true;app.quit()}}]))}
function applyAutoStart(){let option={openAtLogin:settings.autoStart,openAsHidden:true};if(!app.isPackaged){option.path=process.execPath;option.args=[ROOT,'--hidden']}app.setLoginItemSettings(option)}
function updateStatus(message,ready=false){win?.webContents.send('update-status',{message,ready,version:app.getVersion()})}
function setupUpdater(){autoUpdater.autoDownload=true;autoUpdater.autoInstallOnAppQuit=true;autoUpdater.on('checking-for-update',()=>updateStatus('Đang kiểm tra cập nhật…'));autoUpdater.on('update-not-available',()=>updateStatus(`Đang dùng bản mới nhất v${app.getVersion()}`));autoUpdater.on('update-available',i=>updateStatus(`Đang tải phiên bản ${i.version}…`));autoUpdater.on('download-progress',p=>updateStatus(`Đang tải cập nhật ${Math.round(p.percent)}%…`));autoUpdater.on('update-downloaded',i=>{updateStatus(`Phiên bản ${i.version} đã sẵn sàng`,true);new Notification({title:'Đã tải bản cập nhật',body:'Mở dashboard và khởi động lại để cập nhật.'}).show()});autoUpdater.on('error',e=>updateStatus(`Không thể cập nhật: ${e.message}`));if(app.isPackaged)setTimeout(()=>autoUpdater.checkForUpdates(),10000)}
function setSettings(x){settings={...settings,...x};applyAutoStart();schedule();if(win){win.setAlwaysOnTop(settings.alwaysOnTop);win.setSize(settings.mini?360:520,settings.mini?330:700,true)}save();publish({...data,settings});return settings}
app.on('second-instance',()=>{win?.show();win?.focus()});app.whenReady().then(()=>{app.setAppUserModelId('local.codex.usage.tray');applyAutoStart();createWindow();tray=new Tray(icon());tray.on('click',()=>win.isVisible()?win.hide():win.show());tray.on('balloon-click',()=>{win.show();win.focus()});menu();tray.displayBalloon({title:'Codex Usage Monitor',content:'Đang chạy dưới khay hệ thống. Nhấp icon xanh–tím để mở dashboard.',iconType:'info',largeIcon:true});schedule();launch(false);setupUpdater()});
ipcMain.handle('get-state',()=>({...data,settings,history}));ipcMain.handle('save-settings',(_,x)=>setSettings(x));ipcMain.on('refresh',()=>{startFast();read()});ipcMain.on('login',login);ipcMain.on('hide',()=>win.hide());app.on('window-all-closed',()=>{});app.on('before-quit',()=>{app.isQuitting=true;save();closeChrome()});
ipcMain.handle('export-history',async()=>{let r=await dialog.showSaveDialog(win,{defaultPath:'codex-usage-history.csv',filters:[{name:'CSV',extensions:['csv']}]});if(r.canceled)return false;let csv='time,limit,remaining\n'+history.map(x=>`${new Date(x.at).toISOString()},${x.kind},${x.remaining}`).join('\n');fs.writeFileSync(r.filePath,'\ufeff'+csv);return true});
ipcMain.handle('clear-history',()=>{history=[];save();publish({...data,history},false);return true});
ipcMain.handle('logout',async()=>{await closeChrome();try{fs.rmSync(PROFILE,{recursive:true,force:true})}catch{};data={status:'Đã đăng xuất',connection:'error',updatedAt:null,stale:true,limits:[]};history=[];save();publish(data,false);return true});
ipcMain.handle('check-update',async()=>{if(!app.isPackaged){updateStatus('Auto-update chỉ hoạt động trên bản đã cài');return false}await autoUpdater.checkForUpdates();return true});ipcMain.on('install-update',()=>autoUpdater.quitAndInstall(false,true));
